int send(char*);
int parse(char**);
void writebday(const char*, const char*);
int validate(char*);
void clearbdays();
void hbdlisten();
char *checkconfig(const char*);
int writeconfig(const char*, const char*);
int editconfig(const char*,const char*);
void stripnewline(char *);